### PR TITLE
API for listing Vendors

### PR DESCRIPTION
**Pull request by vasundhara-digitalairtech**
Fixes Issue #185

### CODE REVIEW

**Review by damianlegawiec — COMMENTED** [review]
@vasundhara-digitalairtech could you also add request specs for this endpoint?

**Comment by adhik-mehta** [comment]
@damianlegawiec  I have added request specs in readme for this endpoint.

**Comment by damianlegawiec** [comment]
> 
> 
> @damianlegawiec  I have added request specs in readme for this endpoint.

I mean automatic request specs. We cannot merge new features without tests.

https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec

**Comment by vasundhara-digitalairtech** [comment]
errors with specs fixed

**Review by damianlegawiec — APPROVED** [review]
Thanks @vasundhara-digitalairtech 👏

**Pull request merged**
