### PR TITLE
Support Spree 4.5 (with compatibility)

### PR DESCRIPTION
**Pull request by JoseMPena**
Based off [JuanseGimenez](https://github.com/JuanseGimenez/spree_multi_vendor/tree/fix-spree-bump-4.5.0)'s PR. Please refer to that link for details.

### CODE REVIEW

**Comment by Juanse-Gimenez** [comment]
I think this issue will be fix on prevoius PR https://github.com/spree-contrib/spree_multi_vendor/pull/216

**Comment by rafalcymerys** [comment]
@nciemniak this one too :)

**Comment by rafalcymerys** [comment]
Hi @JoseMPena could you please describe a bit more what's the scope of changes in your PR (compared vs the @JuanseGimenez PR that you mentioned)?

**Comment by JoseMPena** [comment]
> 

Hi @rafalcymerys Thanks for looking into this. The only relevant change here (vs @JuanseGimenez 's PR) is in `base_controller_decorator.rb`, Here we're also decorating V2::BaseController, not only V1

**Comment by rafalcymerys** [comment]
@JoseMPena thanks. I'm looking through the code, but I can't find any usages of current_spree_vendor or set_vendor_id in the V2 endpoints. Is it needed there?

**Comment by JoseMPena** [comment]
> @JoseMPena thanks. I'm looking through the code, but I can't find any usages of current_spree_vendor or set_vendor_id in the V2 endpoints. Is it needed there?

Hi @rafalcymerys You're right!, it can be decorated locally in our project, no need to overload the base repo. Thank you very much for the time invested in this. I'm closing this PR.

**Pull request closed without merging**
